# Exciting new World: Tensor

## This notebook is part of the first assignment.
 Pytorch is an open source neural network library, tensors are part of torch library and are defined as the multidimensional matrix Containing elements of single data type.
- torch.arange 
- torch.sin
- torch.true_divide
- torch.where 
- torch.bitwise_not

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.arange

torch.arange returns a 1-D tensor of size [end-start/step] 

In [4]:
# Example 1 - working 
torch.arange(7)

tensor([0, 1, 2, 3, 4, 5, 6])

This function returns 1-D tensor from 0 to 6

In [8]:
# Example 2 - working
d2 = torch.arange(2,5,0.5)
print(d2)
print(d2.dtype)

tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])
torch.float32


we can see here that we can specify the step (default:1) to specify the differenc. Also notice dtype changed from integer to float.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(5,7,-1)

RuntimeError: upper bound and larger bound inconsistent with step sign

Here we have mentioned step as negative thus we cant possibly reach the larger bound.

Very useful when we need evenly spaced large 1-D tensors.

## Function 2 - torch.sin(input)

Torch.asin() returns the new tensor with sine of elements of the input tensor.

In [19]:
# Example 1 - working
d = torch.tensor([0.523599, 1.5708])
print(torch.sin(d))

tensor([0.5000, 1.0000])


Example returning sine of 30 degrees and 90 degrees respectively.

In [16]:
# Example 2 - working
d = torch.randn(2,2)
print(d)
print(torch.sin(d))

tensor([[-0.2024,  0.7731],
        [ 0.0709,  1.3345]])
tensor([[-0.2010,  0.6984],
        [ 0.0708,  0.9722]])


Sine of random values, this shows sine can be applied to N-D tensor

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
print(torch.sin([2,3]))

TypeError: sin(): argument 'input' (position 1) must be Tensor, not list

We need tensor as an input object, thus when we pass list as object functions returns an error

Very useful in Trigonometric operations along with cos, tan, arcsin and other functions. 

## Function 3 - torch.true_divide

torch.true_divide performs division with output in floating point datatype, equivalent to torch.div which is now deprecated.

In [24]:
# Example 1 - working
d = torch.tensor([5,10])
print(torch.true_divide(d,5))

tensor([1., 2.])


Here we have passed D as input to the function which divided tensor elements by 5.

In [25]:
# Example 2 - working
dividend = torch.tensor([4,10])
divisor = torch.tensor([2,5])
print(torch.true_divide(dividend, divisor))

tensor([2., 2.])


Above example shows that we can divide two tensors with elements dividing their respective elements.

In [26]:
# Example 3 - breaking (to illustrate when it breaks)
dividend = torch.tensor([4,10,3])
divisor = torch.tensor([2,5])
print(torch.true_divide(dividend, divisor))

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

The divisor and the dividend should be of same dimensions.

Very usefull function in data science, when we need to distribute the data among several iterations/epochs

## Function 4 - torch.where

returns the elements from two inputs depending upon the given condition

In [32]:
# Example 1 - working
d = torch.randn(3,2)
print(d)
c = torch.ones(3,2)
print(torch.where(d>0,d,c))

tensor([[-0.0695,  0.0984],
        [-0.4833, -0.0473],
        [ 1.5297, -0.4443]])
tensor([[1.0000, 0.0984],
        [1.0000, 1.0000],
        [1.5297, 1.0000]])


We have removed all the negative elements in the d tensor using where function, replacing them with 1.

In [38]:
# Example 2 - working
d = torch.randn(3,3)
print(d)
c = torch.ones(3,3)
print(torch.where((d>0) |( d <0) ,d,c))

tensor([[ 0.5124, -0.0696, -1.2565],
        [ 0.4914,  0.4956,  0.2960],
        [-0.6134, -0.1725, -0.5661]])
tensor([[ 0.5124, -0.0696, -1.2565],
        [ 0.4914,  0.4956,  0.2960],
        [-0.6134, -0.1725, -0.5661]])


We can add logical operators in the where clause to suit our needs.

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
d = torch.randn(3,2)
print(d)
c = torch.ones(3,3)
print(torch.where(d>0,d,c))

tensor([[-0.8907, -0.9563],
        [-1.4838, -0.3195],
        [-0.6612, -0.7558]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

input dimesions must match for both the tensors.

This function can be effectively used to remove desired elements from the tensor.

## Function 5 - torch.bitwise_not

computes the bitwise not of the tensor, input should be integer or boolean

In [50]:
# Example 1 - working
d = torch.tensor([0,1], dtype=torch.bool)
print(torch.bitwise_not(d))

tensor([ True, False])


Example with tensor as boolean values.

In [52]:
# Example 2 - working
d = torch.tensor([2,1])
print(torch.bitwise_not(d))

tensor([-3, -2])


Example with integral values

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
d = torch.tensor([2,1.])
print(torch.bitwise_not(d))

RuntimeError: "bitwise_not_cpu" not implemented for 'Float'

Input contained float values for which it is throwing error, bitwise not is implemented for integer and boolean 

Can be used in need of logical operations.

## Conclusion

These are few of the many functions currently supported under tensor, for more please refer the official documentation.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [3]:
!pip install jovian --upgrade --quiet

In [21]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
